name: Continuous Delivery (Test)

on:
    push:
        branches: ['release/*']

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Clone
              uses: actions/checkout@v1

            - name: Install .NET
              uses: actions/setup-dotnet@v1
              with:
                  # NOTE: Do not change this version without also updating MSIExtract.AppxPackage/Directory.Build.targets
                  dotnet-version: 3.1.300

            - name: Configure Visual Studio
              uses: microsoft/setup-msbuild@v1.0.0

            - name: Update Versions
              id: update_version
              run: |
                $ref = "${{ github.ref }}"
                if ($ref.StartsWith("refs/heads/release/")) {
                  $ref = $ref.Replace("refs/heads/release/", "")
                }

                $version = [regex]::Replace($ref, '^v?(\d+(?:\.\d+){1,2})(-.+)?$', '$1$2')
                $json = Get-Content .\version.json | ConvertFrom-Json
                $json.version = $version
                $json | ConvertTo-Json | Set-Content .\version.json

                $version = [regex]::Replace($ref, '^v?(\d+(?:\.\d+){1,2})(-.+)?$', '$1')
                if ($version -ne '') {
                  [xml]$manifest = Get-Content '.\src\MSIExtract.AppxPackage\Package.appxmanifest'
                  $manifest.Package.Identity.Version = "$($version).0"
                  $manifest.Save('.\src\MSIExtract.AppxPackage\Package.appxmanifest')
                }

                echo "::set-output name=version::$version"

            - name: Build
              working-directory: ./src/MSIExtract.AppxPackage
              run: |
                & MSBuild.exe /nologo /restore /bl /m /p:Configuration=Release /p:Platform=x64 `
                  /p:BuildAppxUploadPackageForUap=true `
                  /p:AppxBundle=Always `
                  /p:AppxPackageSigningEnabled=true `
                  /p:PackageCertificateThumbprint=492019107FC952A6183CE97F474F9FACB147E7BC `
                  /p:PackageCertificateKeyFile=.\cert.pfx `
                  /p:PackageCertificatePassword=1234 `
                  /t:Publish

            - name: Prepare Assets for Upload
              working-directory: ./bin/AppxPackages
              run: |
                dir -Recurse -Include *.msixupload, *.msixbundle
                $uploads = (dir *.msixupload)
                if ($uploads.Length -ne 0) {
                  mv $uploads[0].FullName MSIViewer_${{ steps.update_version.outputs.version }}.msixupload -Verbose
                } else {
                  Write-Error "Could not find any msixupload files"
                }

                $bundles = (dir *_Test | dir -Include *.msixbundle)
                if ($bundles.Length -ne 0) {
                  mv $bundles[0].FullName MSIViewer_${{ steps.update_version.outputs.version }}_Sideload.msixbundle -Verbose
                } else {
                  Write-Error "Could not find any msixbundle files"
                }

            - name: Upload Store Assets
              uses: actions/upload-artifact@v1
              with:
                  name: "MSI Viewer ${{ steps.update_version.outputs.version }} Store.msixupload"
                  path: bin/AppxPackages/MSIViewer_${{ steps.update_version.outputs.version }}.msixupload

            - name: Upload Sideload Assets
              uses: actions/upload-artifact@v1
              with:
                  name: "MSI Viewer ${{ steps.update_version.outputs.version }} Sideload.msixbundle"
                  path: bin/AppxPackages/MSIViewer_${{ steps.update_version.outputs.version }}_Sideload.msixbundle
