name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      name: Clone
    - uses: actions/setup-dotnet@v1
      name: Install .NET Core
      with:
        dotnet-version: 3.1.300
    - uses: microsoft/setup-msbuild@v1.0.0
      name: Configure Visual Studio
    - name: Restore
      working-directory: ./src
      run: |
        & MSBuild.exe /nologo /t:Restore
    - name: Build
      working-directory: ./src/MSIExtract
      run: |
        & MSBuild.exe /nologo /m /p:Configuration=Release /p:Platform=x64
