name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - uses: seanmiddleditch/gha-setup-vsdevenv@master
      name: Configure Visual Studio
      id: vsdevcmd
    - name: Restore
      run: "${{ steps.vsdevcmd.outputs.install_path }}\\MSBuild\\Current\\bin\\msbuild.exe" /nologo /t:Restore
      working-directory: ./src/Sunburst.WixSharpApp
    - name: Build
      run: "${{ steps.vsdevcmd.outputs.install_path }}\\MSBuild\\Current\\bin\\msbuild.exe" /nologo /m /p:Configuration=Release /p:Platform=x64
      working-directory: ./src/Sunburst.WixSharpApp
